version: "3.8"

services:
  postgres_db:
    image: postgres:14.0
    ports:
      - "5436:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/database.env
    container_name: postgres_cinema

  backend_python:
    build: .
    volumes:
      - .:/code/
    ports:
      - '8000:8000'
    container_name: cinema_reservations_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres_db
    env_file:
      - ./env/.env
