# Generated by Django 4.0.5 on 2022-07-02 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations_app', '0002_cinemahallmodel_rename_author_authormodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=255)),
                ('booked_seats', models.ManyToManyField(related_name='reservation_seat', to='reservations_app.seatmodel')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations_app.repertoiremodel')),
            ],
        ),
    ]
