# Generated by Django 4.0.5 on 2022-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_app', '0003_seatmodel_reservationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='reservations_app.moviegenresmodel'),
        ),
    ]
