# Generated by Django 4.0.5 on 2022-07-06 08:10

from django.db import migrations

from reservations_app.models import SeatModel


def create_seats(apps, schema_editor):
    letters_list = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

    for letter in letters_list:
        for i in range(1, 13):
            seat = SeatModel.objects.create(position=f'{letter}{i}')


class Migration(migrations.Migration):
    dependencies = [
        ('reservations_app', '0004_moviegenresmodel_moviemodel_genre'),
    ]

    operations = [
        migrations.RunPython(create_seats)
    ]
